services:
  # Search Service (あなたのアプリケーション)
  search-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      # 環境変数で接続先を指定 (コンテナ名がホスト名になる)
      - SEARCH_ELASTICSEARCH_ADDRESSES=http://elasticsearch:9200
      - SEARCH_QDRANT_ADDRESS=qdrant:6333
    depends_on:
      - elasticsearch
      - qdrant
    networks:
      - search_net

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 開発用にメモリ使用量を制限
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - search_net

  # Qdrant
  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports:
      - "6333:6333" # gRPC port
      - "6334:6334" # REST port
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - search_net

volumes:
  es_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  search_net:
    driver: bridge