grpc:
  port: 50051

logger:
  level: "info"

elasticsearch:
  addresses:
    - "http://localhost:9200"
  username: ""
  password: ""

qdrant:
  address: "localhost:6334"
  apiKey: ""

kafka:
  brokers:
    - "localhost:9092"
  groupId: "search-service-consumer"
  topic: "search.indexing.requests"
