grpc:
  port: 50051

logger:
  level: "info"

elasticsearch:
  addresses:
    - "http://localhost:9200"
  username: ""
  password: ""

qdrant:
  address: "localhost:6334"
  apiKey: ""

kafka:
  brokers:
    - "localhost:9092"
  groupId: "search-service-consumer"
  topic: "search.indexing.requests"

search:
  hybrid:
    weights:
      keyword: 0.5
      vector: 0.5

observability:
  metrics:
    address: ":9464"
  tracing:
    endpoint: "jaeger:4318"
    insecure: true
