grpc:
  port: 50051

logger:
  level: "info"

# docker-compose.yml内の環境変数で上書きされるため、
# ここはローカルで `go run` する場合などのフォールバック値となります。
elasticsearch:
  addresses:
    - "http://localhost:9200"
  username: ""
  password: ""

qdrant:
  address: "localhost:6333"
  apiKey: ""