name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate & Test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      GO_VERSION: "1.24.7"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Install Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Ensure Go bin on PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Download dependencies
        run: go mod download

      - name: Install Go tools
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.24.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.3

      - name: Run aggregated CI checks
        run: make ci

      - name: Run end-to-end tests
        run: make test-e2e

      - name: Run integration tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: make test-integration

      - name: Build Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker build -t search-service:${{ github.sha }} .
